language: node_js
node_js:
    - "12"

notifications:
  email:
    on_success: never
    on_failure: never

before_install:
  - sudo apt-get update
  - npm update -g npm
  - npm install -g grunt-cli

install:
  - npm install zeromq@6.0.0-beta.6 --zmq-shared
  - npm install
  - npm rebuild

cache:
  directories:
    - node_modules

script:
  - npm run test
